---
- name: Create my credentials
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  collections:
  - ansible.controller

  tasks:
  - name: Making sure the credential exists. For the sake of the demo we didn't vault the password
    ansible.controller.credential:
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      name: "{{ customer }} root password"
      organization: "{{ customer }} org"
      state: present
      kind: ssh
      inputs:
        username: root
        password: redhat01
