---
- name: Create my jobs
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  collections:
  - ansible.controller

  tasks:
  - name: Making sure the job exists
    ansible.controller.job_template:
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      name: "{{ customer }} job"
      organization: "{{ customer }} org"
      state: present
      project: "{{ customer }} project"
      inventory: "{{ customer }} inventory"
      playbook: "playbook.yml"
      credentials:
      - "{{ customer }} root password"
