---
- name: 💥💥💥 Simulate a disaster! 💥💥💥
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  collections:
  - ansible.controller

  tasks:
  - name: 🧨 Nuke the org 🧨
    ansible.controller.organization:
      name: "{{ customer }} org"
      state: absent
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False

  - name: 🧨 Nuke the project 🧨
    ansible.controller.project:
      name: "{{ customer }} project"
      state: absent
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False

  - name: 🧨 Nuke the job 🧨
    ansible.controller.job_template:
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      name: "{{ customer }} job"
      state: absent
